In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import geoplot

ModuleNotFoundError: No module named 'geopandas'

In [4]:
x = np.random.randint(low=0,high=6,size=10)
y = np.random.randint(low=0,high=6,size=10)

In [6]:
for pair in zip(x,y):
    print(pair)

(0, 4)
(4, 0)
(3, 4)
(0, 5)
(3, 1)
(3, 3)
(4, 4)
(3, 5)
(5, 5)
(4, 3)


In [9]:
H, xedges, yedges = np.histogram2d(x, y)

In [10]:
H=H.T

In [11]:
print(H)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 1.]]


In [12]:
xedges, yedges

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]),
 array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]))

In [13]:
sum(H)

array([2., 0., 0., 0., 0., 0., 4., 0., 3., 1.])

In [14]:
sum(sum(H))

10.0

In [17]:
xcenters = (xedges[:-1] + xedges[1:]) /2

In [18]:
xcenters

array([0.25, 0.75, 1.25, 1.75, 2.25, 2.75, 3.25, 3.75, 4.25, 4.75])

In [19]:
%whos

Variable   Type       Data/Info
-------------------------------
H          ndarray    10x10: 100 elems, type `float64`, 800 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pair       tuple      n=2
pd         module     <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
x          ndarray    10: 10 elems, type `int32`, 40 bytes
xcenters   ndarray    10: 10 elems, type `float64`, 80 bytes
xedges     ndarray    11: 11 elems, type `float64`, 88 bytes
y          ndarray    10: 10 elems, type `int32`, 40 bytes
yedges     ndarray    11: 11 elems, type `float64`, 88 bytes


In [20]:
import geopandas
import geoplot

ModuleNotFoundError: No module named 'geopandas'